version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_SERVER_URL: https://${MINIO_PUBLIC_URL:-localhost}:${MINIO_API_PORT:-9000}
      MINIO_BROWSER_REDIRECT_URL: https://${MINIO_PUBLIC_URL:-localhost}:${MINIO_CONSOLE_PORT:-9001}
    ports:
      - ${MINIO_API_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    volumes:
      - minio-data:/data
      - ./cert.pem:/root/.minio/certs/public.crt:ro
      - ./key.pem:/root/.minio/certs/private.key:ro
    restart: unless-stopped

volumes:
  minio-data:
    name: minio_data_volume
