services:

  server1:
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    container_name: mlox-server1
    restart: always
    networks:
      - mlox_net
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 4.1G
        reservations:
          cpus: '1.0001'
          memory: 0.1G

  server2:
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    container_name: mlox-server2
    restart: always
    networks:
      - mlox_net

  mlox:  
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: mlox-ui
    ports:
      - "8501:8501"
    environment:
      - MLOX_DEBUG=true
      - MLOX_CONFIG_USER=mlox-user
      - MLOX_CONFIG_PASSWORD=mlox-secret-passphrase
    networks:
      - mlox_net

networks:
  mlox_net: 
    name: mlox-network
    driver: bridge 
