services:

  mlox:  
    image: drbusysloth/mlox:latest
    restart: always
    container_name: mlox
    ports:
      - "8501:8501"
    environment:
      - MLOX_DEBUG=false
      - MLOX_PROJECT_DIR=/var/lib/mlox/projects
    volumes:
      - mlox_projects:/var/lib/mlox/projects
    networks:
      - mlox_net

networks:
  mlox_net: 
    name: mlox-network
    driver: bridge 

volumes:
  mlox_projects:
