FROM python:3.11-slim

ENV PYTHONPATH=.

RUN apt-get -y update; apt-get -y install curl
RUN apt-get -y install bash
RUN apt-get -y install git

RUN curl -s -N https://pyenv.run | bash
RUN pip install mlflow
RUN pip install 'mlflow[extras]'

RUN pip uninstall --yes pydantic
RUN pip install pydantic==1.10.14