# FROM ghcr.io/mlflow/mlflow:latest
FROM python:3.11-slim

ENV PYTHONPATH=.

RUN pip install mlflow
RUN pip install 'mlflow[genai]'

RUN pip uninstall --yes pydantic
RUN pip install pydantic==1.10.14

COPY mlflow_llm_config.yaml /home/

# EXPOSE 5050

# ENV OPENAI_API_KEY=sk-??
# ENTRYPOINT mlflow deployments start-server --config-path /home/mlflow_llm_config.yaml --port 5050 --host 0.0.0.0