receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          cert_file: /etc/cert.pem
          key_file: /etc/key.pem
      http:
        endpoint: 0.0.0.0:4318
        tls:
          cert_file: /etc/cert.pem
          key_file: /etc/key.pem

  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      memory:
      load:
      disk:
      filesystem:
      network:

exporters:
<<<<<<< ours
__NEWRELIC_EXPORTER_BLOCK__
__GRAFANA_EXPORTER_BLOCK__
__INFLUX_EXPORTER_BLOCK__
=======
  otlphttp/newrelic:
    endpoint: ${env:MY_OTEL_RELIC_ENDPOINT}
    headers:
      api-key: ${env:MY_OTEL_RELIC_KEY}

  otlphttp/grafana:
    endpoint: ${env:MY_OTEL_GRAFANA_ENDPOINT}
    headers:
      Authorization: ${env:MY_OTEL_GRAFANA_AUTH}

  otlphttp/influxdb:
    endpoint: ${env:MY_OTEL_INFLUX_ENDPOINT}
    headers:
      Authorization: ${env:MY_OTEL_INFLUX_AUTH}
>>>>>>> theirs

  file:
    path: /etc/otelcol/telemetry.json
    rotation:
      max_megabytes: 10
      max_backups: 5
  debug:
    verbosity: detailed

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"
    tls:
      cert_file: /etc/cert.pem
      key_file: /etc/key.pem
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug, file__OPTIONAL_EXPORTERS__]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch, memory_limiter]
      exporters: [debug, file__OPTIONAL_EXPORTERS__]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug, file__OPTIONAL_EXPORTERS__]
