blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/BusySloths/mlox/discussions
    about: Ask questions, share ideas, and discuss MLOX with the community
  - name: 📖 Documentation
    url: https://github.com/BusySloths/mlox/wiki
    about: Check our wiki for guides, tutorials, and detailed documentation
  - name: 📧 Contact Maintainers
    url: mailto:contact@mlox.org
    about: Contact the maintainers directly for security issues or private matters