version: '3.8'


services:

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.105.0
    restart: always
    environment:
      - MY_OTEL_RELIC_ENDPOINT=${OTEL_RELIC_ENDPOINT}
      - MY_OTEL_RELIC_KEY=${OTEL_RELIC_KEY}
    command: ["--config=/etc/otel-collector-config.yaml", "--feature-gates=-component.UseLocalHostAsDefaultHost"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./cert.pem:/etc/cert.pem
      - ./key.pem:/etc/key.pem
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "13133:13133"  # health check