receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
  debug:

  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    target_info:
      enabled: true
      
  otlp: 
    endpoint: jaeger-all-in-one:4317  # works, but why?
    # endpoint: 0.0.0.0:4317  # does not work
    # endpoint: jaeger-all-in-one:14250  # does not work
    tls:
      insecure: true    

  otlphttp:
    endpoint: https://otlp.eu01.nr-data.net:4317
    headers:
      api-key: "eu01xxa33b125351c57e587343f28975FFFFNRAL"

processors:
  batch:

connectors:
  spanmetrics:
    namespace: myspanmetrics

extensions:
  health_check:
    endpoint: "0.0.0.0:13133" 
    path: "/health/status" 
    check_collector_pipeline: 
      enabled: true 
      interval: "5m" 
      exporter_failure_threshold: 5   
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  telemetry:
    logs:
      level: debug 
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]    
      processors: [batch]
      exporters: [otlp, spanmetrics, debug, otlphttp]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [debug, prometheus, otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]