version: '3.8'
services:
  mlflow:
    build:
      context: .
      dockerfile: dockerfile-mlflow-mlserver
    restart: always
    container_name: mlflow_mlserver_${PORT}
    ports:  # expose for internal
        - ${PORT}:5002
    command: mlflow models serve -m models:/${MLFLOW_MODEL} -p 5002 -h 0.0.0.0 -w 2 --enable-mlserver
