version: "3.8"

services:
  openbao:
    image: openbao/openbao:2.5.4
    restart: unless-stopped
    container_name: ${OPENBAO_STACK_PREFIX}_openbao
    environment:
      SKIP_SETCAP: "1"
    entrypoint: ["bao"]
    command: ["server", "-config=/openbao/config/openbao.hcl"]
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/openbao/data
      - ./logs:/openbao/logs
      - ./cert.pem:/openbao/tls/cert.pem:ro
      - ./key.pem:/openbao/tls/key.pem:ro
      - ./config/openbao.hcl:/openbao/config/openbao.hcl:ro
    ports:
      - "${OPENBAO_PORT}:8200"
