version: '3.8'
services:
  mlflow-llm:
    build:
      context: .
      dockerfile: dockerfile-mlflow
    # restart: always
    container_name: mlflow-llm
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:  # expose for internal
      - 5050:5050
    command: mlflow deployments start-server --config-path /home/mlflow_llm_config.yaml --port 5050 --host 0.0.0.0

  mlflow:
    build:
      context: .
      dockerfile: dockerfile-mlflow
    environment:
      - MLFLOW_DEPLOYMENTS_TARGET=http://mlflow-llm:5050/
      - MLFLOW_TRACKING_USERNAME=admin
      - MLFLOW_TRACKING_PASSWORD=password
    restart: always
    container_name: mlflow
    ports:  # expose for internal
        - 5002:5002
    command: mlflow server --host 0.0.0.0:5002 --app-name basic-auth
    depends_on:
      - mlflow-llm