name: Code Coverage Report

on:
  workflow_dispatch:

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:  
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          pip install -r requirements.txt
      - name: Generate Code Coverage
        run: |
            coverage run -m pytest tests
            coverage lcov
      - name: Code Coverage Report
        uses: qltysh/qlty-action/coverage@v1
        with:
            token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
            files: coverage.lcov