name: Deploy to PYPI

on:
  workflow_dispatch:
    # Example input for the workflow 
    inputs:
      name:
        description: 'Your input here'
        default: 'I have nothing to say'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          pip install --upgrade setuptools
          pip install --upgrade setuptools-git-versioning
      - name: Test setuptools-git-versioning
        run: | 
          python -m setuptools_git_versioning
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 mlox/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 mlox/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Unit Tests
        run: |
          task tests:unit:run
      - name: Prepare Distribution
        run: |
          python -m build
          twine check --strict dist/*
          pip install -U packaging
          twine check --strict dist/*
      - name: Deploy
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}        
        
