name: Docker Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Docker tag to publish (e.g. v1.2.3)
        required: true
        type: string
      latest:
        description: Also push the 'latest' tag
        required: false
        default: false
        type: boolean
      platforms:
        description: Target platforms (comma-separated)
        required: false
        default: linux/amd64,linux/arm64
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      IMAGE_NAME: drbusysloth/mlox
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          set -euo pipefail
          TAG_INPUT='${{ github.event.inputs.tag }}'
          if [ -z "$TAG_INPUT" ]; then
            echo "Tag input is required" >&2
            exit 1
          fi
          TAGS="${IMAGE_NAME}:${TAG_INPUT}"
          if [ "${{ github.event.inputs.latest }}" = "true" ]; then
            TAGS="$TAGS,${IMAGE_NAME}:latest"
          fi
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ github.event.inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

