# [theme]
# base="light"
# # The font family for all text, except code blocks. This can be one of
# # the following:
# # - "sans-serif"
# # - "serif"
# # - "monospace"
# # - the `font` value for a custom font table under [[theme.fontFaces]]
# # - a comma-separated list of these (as a single string) to specify
# #   fallbacks
# # For example, you can use the following:
# # font = "cool-font, fallback-cool-font, sans-serif"
# font = "sans-serif"

# # The radius used as basis for the corners of most UI elements. This can
# # be one of the following: "none", "small", "medium", "large", "full",
# # or the number in pixels or rem. For example, you can use "10px",
# # "0.5rem", or "2rem". To follow best practices, use rem instead of
# # pixels when specifying a numeric size.
# baseRadius = "10px"
# # Sets the root font size (in pixels) for the app, which determines the
# # overall scale of text and UI elements. The default base font size is 16.
# baseFontSize = 14
# # Whether to show a vertical separator between the sidebar and the main
# # content area.
# showSidebarBorder = true
# # Whether to show a border around input widgets.
# showWidgetBorder = true

# [theme]
# base = "light"
# primaryColor = "#607B8B"  # A muted blue-grey
# backgroundColor = "#F0F8FF"  # Very light blue-grey (almost white)
# secondaryBackgroundColor = "#E0ECF8" # Slightly darker blue-grey for widgets
# textColor = "#36454F"  # Dark grey for text
# linkColor = "#4682B4"  # A more distinct blue for links
# codeBackgroundColor = "#D3D3D3" # Light grey for code blocks
# codeFont = "monospace"
# font = "sans-serif"
# headingFont = "sans-serif"
# baseRadius = "0.3rem"
# borderColor = "#A9A9A9" # Medium grey for borders
# showWidgetBorder = true
# baseFontSize = 14
# showSidebarBorder = true

[theme]
base = "dark"
primaryColor = "#008080"  # A professional teal accent
backgroundColor = "#1E1E1E"  # Very dark grey background
secondaryBackgroundColor = "#2D2D2D" # Slightly lighter dark grey for sidebar and widgets
textColor = "#E0E0E0"  # Soft white for primary text
linkColor = "#4682B4"  # Steel blue for links
codeBackgroundColor = "#252526" # Dark background for code blocks
codeFont = "monospace"
font = "sans-serif"
headingFont = "sans-serif"
baseRadius = "0.2rem" # Small radius for a modern, slightly rounded look
borderColor = "#404040" # Dark grey border color for subtle separation
showWidgetBorder = false # No borders around widgets for a cleaner, flatter look
baseFontSize = 16
showSidebarBorder = true # Show sidebar border for clear layout separation

[client]
# Change the visibility of items in the toolbar, options menu,
# and settings dialog (top right of the app).
# Allowed values:
# - "auto"      : Show the developer options if the app is accessed through
#                 localhost or through Streamlit Community Cloud as a developer.
#                 Hide them otherwise.
# - "developer" : Show the developer options.
# - "viewer"    : Hide the developer options.
# - "minimal"   : Show only options set externally (e.g. through
#                 Streamlit Community Cloud) or through st.set_page_config.
#                 If there are no options left, hide the menu.
# Default: "auto"
toolbarMode = "minimal"

[browser]
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false
