[theme]
base = "dark"
primaryColor = "#FF7A59"  # Warm coral for buttons and focus
backgroundColor = "#1A1C1F"  # Neutral charcoal base
secondaryBackgroundColor = "#24272B"  # Soft graphite for cards
textColor = "#F3F4F6"  # Subtle off-white text
linkColor = "#4AA8FF"  # Cool contrast for links
linkUnderline = false
codeBackgroundColor = "#1F2226"
dataframeHeaderBackgroundColor = "#262A2F"
borderColor = "#40454F"
dataframeBorderColor = "#4A505B"
showWidgetBorder = true
showSidebarBorder = true
baseRadius = "0.7rem"
buttonRadius = "1.35rem"
baseFontSize = 16
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
baseFontWeight = 400
codeFontWeight = 400
headingFontSizes = { h1 = 36, h2 = 28, h3 = 24, h4 = 20, h5 = 18, h6 = 16 }
headingFontWeights = { h1 = 600, h2 = 600, h3 = 600, h4 = 500, h5 = 500, h6 = 500 }

chartCategoricalColors = [
    "#FF7A59",  # Warm coral
    "#FFBE0B",  # Punchy amber
    "#F15BB5",  # Bold magenta
    "#00BBF9",  # Bright cyan
    "#9B5DE5",  # Deep violet
    "#00F5D4",  # Electric mint
    "#FF9F1C",  # Tangy orange
    "#577590"   # Slate blue
]
chartSequentialColors = [
    "#121315",
    "#181A1D",
    "#1F2226",
    "#272A30",
    "#303339",
    "#3A3D44",
    "#444850",
    "#4F5460",
    "#5C6170",
    "#6A6F82"
]

greenColor = "#00F5D4"
greenBackgroundColor = "#0E2E2C"
greenTextColor = "#E4FFF9"
yellowColor = "#FFBE0B"
yellowBackgroundColor = "#332A12"
yellowTextColor = "#140F04"
violetColor = "#9B5DE5"
violetBackgroundColor = "#261C36"
violetTextColor = "#F8F3FF"
blueColor = "#00BBF9"
blueBackgroundColor = "#142C38"
blueTextColor = "#E5F9FF"
orangeColor = "#FF9F1C"
orangeBackgroundColor = "#331F10"
orangeTextColor = "#FFF0E0"
redColor = "#F15BB5"
redBackgroundColor = "#341226"
redTextColor = "#FFE6F4"
grayColor = "#8892A6"
grayBackgroundColor = "#2B2E36"
grayTextColor = "#F2F3F8"

[theme.sidebar]
primaryColor = "#F15BB5"
backgroundColor = "#1C1F24"
secondaryBackgroundColor = "#282C33"
textColor = "#F7F0F4"
linkColor = "#5CD6FF"
linkUnderline = false
codeBackgroundColor = "#21252B"
borderColor = "#434A55"
dataframeBorderColor = "#4E5563"
showWidgetBorder = true
baseRadius = "0.65rem"
buttonRadius = "1.3rem"

greenColor = "#42FFD9"
yellowColor = "#FFD45C"
violetColor = "#B58DFF"
blueColor = "#6AD9FF"
orangeColor = "#FFB97A"
redColor = "#FF7FBF"
grayColor = "#9CA6B8"
[client]
# Change the visibility of items in the toolbar, options menu,
# and settings dialog (top right of the app).
# Allowed values:
# - "auto"      : Show the developer options if the app is accessed through
#                 localhost or through Streamlit Community Cloud as a developer.
#                 Hide them otherwise.
# - "developer" : Show the developer options.
# - "viewer"    : Hide the developer options.
# - "minimal"   : Show only options set externally (e.g. through
#                 Streamlit Community Cloud) or through st.set_page_config.
#                 If there are no options left, hide the menu.
# Default: "auto"
toolbarMode = "minimal"

[browser]
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false
